### ISSUE TITLE
tab character not being printed in less output

### ISSUE THREAD

**Issue by busterbeam** [gwsw/less#292] opened 2022-10-22 10:48 UTC
I use tab key indentation in my plain text files, I realized that when examining them in `less` the character is a series of spaces.  Maybe you use spaces because of your `-x` parameter but can you not work around to changing how the terminal outputs tabstops??

it is some what helpful to know I could copy text out of less and know it is tab stopped and not going to mess up my plain text

**Comment by gwsw** [comment] 2022-10-22 15:16
It would be possible, but rather challenging to do this. For example, if the text had long lines which wrapped, then depending on the relationship between the tabstop settings and the width of the terminal, less would need to set different terminal tabs before printing every single line. Also if the text were scrolled horizontally with the arrow keys, tabs would need to be set to a "shifted" version of the -x settings. And I don't believe there's any way to read tab settings from a terminal, so when less exits there would be no way to restore tab settings to what they were before less was run. I notice that vim also uses spaces rather than hard tabs, presumably for similar reasons. 

There is already an open git issue #152 requesting this, so I will merge this with issue with that one.

**Comment by busterbeam** [comment] 2022-10-22 15:26
Thanks, will follow that issue.  Sorry I didn't pick up on that

**Comment by gwsw** [comment] 2022-10-22 16:05
Duplicate of #152.

**Closed by gwsw** 2022-10-22 16:05 UTC
