### ISSUE TITLE
less 587 makes characters not display compared to 581.2

### ISSUE THREAD

**Issue by d-c-d** [gwsw/less#216] opened 2021-10-22 17:25 UTC
On cygwin, I was used to using silver searcher (ag) with --color and less -R to view data
Extracting just the line of data and creating a test case on the command line

echo -e '\e[1;33m694\e[0m\e[K:#ifdef \e[30;43mUSE_SMT3\e[0m\e[K' | less +/694

displays as
:#ifdef USE_SMT3

I expected behavior like I get with 581.2
694:#ifdef USE_SMT3

where 694 is bright, and USE_SMT3 is highlighted

**Comment by gwsw** [comment] 2021-10-31 22:17
The reported problem should be fixed in 0300ba11976adf24b844511006b1e459617cece8.

@fcpg your issue seems to be unrelated. Please open a new report and provide a sample file showing the problem. I don't see the problem running "man mintty" but my mintty man page may be different from the one you are looking at.

**Comment by gwsw** [comment] 2021-11-09 03:05
This should be fixed in 0300ba11976adf24b844511006b1e459617cece8, available in less-596.

@fcpg, your issue seems to be unrelated to this. Please open a new issue and provide a sample file that demonstrates the problem. I cannot reproduce it using your instructions with "man mintty" on cygwin using less-590.

**Closed** 2021-12-04 04:48 UTC

**Comment by fcpg** [comment] 2022-10-17 14:36
I kept the old 581 version on that cygwin box all that time until I decided to further investigate, and it turned out that there were very old `.less`, `.lesskey` and `.lessx` files lying in homedir *facepalm*
Removing them solved my problem.
