### ISSUE TITLE
Improper ANSI color codes handling

### ISSUE THREAD

**Issue by RomanValov** [gwsw/less#276] opened 2022-09-02 20:07 UTC
Hi,

I'm running Ubuntu 22.04 and using less 590. Found a regression in ANSI color codes handling. The minimal text file to reproduce is attached. It has two lines and regression occurs on a second line. However if I remove first line regression is gone.

Literally it's expected hexadecimal identifier on second line to be all yellow.
However instead I've got only first character is highlighted and color is brightyellow.

Based on my tests the regression was introduced at version 581 (among public releases).

![Screenshot from 2022-09-03 02-06-26](https://user-images.githubusercontent.com/5928128/188228473-d780e7ec-2a2d-46f8-ad2a-e5d3e3e45d5b.png)

[slog.log](https://github.com/gwsw/less/files/9480812/slog.log)

**Comment by gwsw** [comment] 2022-09-02 23:57
That's a pretty odd sequence in the second line, which has a TAB followed by a BACKSPACE. The unexpected behavior seems to be mainly triggered by this attempt to overstrike a TAB. I have a possible fix but I want to do some more testing with a variety of test cases.

**Comment by RomanValov** [comment] 2022-09-04 22:07
Great! Thank you. It also worth to mention if hexadecimal identifier starts with another symbols, i.e. `5` or `7` instead of `3`, the regression is gone also.

**Comment by gwsw** [comment] 2022-09-09 05:27
This should be fixed in 77d419db47a5e1383c648b447bc70e2003d70f3c.

**Closed** 2022-09-25 03:20 UTC
