### ISSUE TITLE
Warn that -K could leave your terminal in reverse video mode

### ISSUE THREAD

**Issue by jidanni** [gwsw/less#68] opened 2020-06-06 17:22 UTC
less 551 man page says

>        -K or --quit-on-intr
>               Causes  less to exit immediately (with status 2) when an interrupt character (usually ^C) is typed.
>               Normally, an interrupt character causes less to stop whatever it is doing and return to its command
>               prompt.   Note that use of this option makes it impossible to return to the command prompt from the
> 

Please add

> Note that this could leave your terminal in reverse video mode, the only cure being the
> reset (1)            - terminal initialization
> command.

Use `SYSTEMD_LESS=-iRXQMK journalctl` then ^C to reproduce.

**Comment by jidanni** [comment] 2020-06-06 17:26
You see with a whopping
```
# journalctl | wc
 578805 7124762 51387566
```
"q" would take several seconds to even just quit (and why? BUG), so one would turn to ^C for instant  relief...

**Comment by gwsw** [comment] 2020-06-06 20:52
It seems to me that this is a problem that should be fixed rather than documented. I don't have journalctl; do you have another way to reproduce it?

**Comment by jidanni** [comment] 2020-06-06 21:25
I couldn't reproduce it with

```
# journalctl > /tmp/j
# LESS=-iRXQMK less /tmp/j
^C
```

so I filed
https://github.com/systemd/systemd/issues/16084
which shows it even happens with smaller --boot input.

**Comment by poettering** [comment] 2020-06-08 16:43
It appears "less" cleans things up properly (i.e. restores the terminal formatting) when it gets SIGINT, but not when it gets SIGTERM). when less is invoked by systemd's auto-paging feature in its various tools then we'll use Linux' PRCTL_PDEATHSIG feature with the SIGTERM signal so that the pager is automatically terminated when our tools die abnormally. SIGTERM is the official way for programs to be asked to exit cleanly (as opposed to SIGINT, which is about the C-c key combo really), hence I'd argue systemd does the right thing there currently, and less should handle SIGTERM the same way it already handles SIGINT if "-K" is used. Does this make sense?

(we could work around this in systemd of course, but that feels like a work-around given, hardcoding expectaions on less' signal handling into our code, even though ideally we'd like to be implementation agnostic when it comes to pagers)

**Comment by jidanni** [comment] 2020-06-08 17:22
Ah, a less bug after all! Reopening.

**Comment by gwsw** [comment] 2020-06-09 16:41
@poettering 
I think handling SIGTERM like SIGINT probably makes sense. Regarding your statement "less should handle SIGTERM the same way it already handles SIGINT if "-K" is used", I think you intended this to be parsed as "less should handle SIGTERM the same way it already handles (SIGINT if "-K" is used)", not "(less should handle SIGTERM the same way it already handles SIGINT) if "-K" is used", correct? In other words, the handling of SIGTERM should not be affected by the -K flag.

**Comment by gwsw** [comment] 2020-06-09 22:28
I just reviewed the code and it looks like less already handles SIGTERM almost the same way as it handles SIGINT with -K. The only difference I see is the exit status (2 for SIGINT and 15 for SIGTERM).  Can someone provide a means to reproduce the problem?

**Comment by gwsw** [comment] 2023-01-03 08:56
Closing as not reproducible.

**Closed by gwsw** 2023-01-03 08:56 UTC
Labels: question
