### ISSUE TITLE
less always checks for a terminal on standard error, not standard output

### ISSUE THREAD

**Issue by zanchey** [gwsw/less#145] opened 2021-04-06 14:22 UTC
(From fish-shell/fish-shell#7863)

4d4e6f467 introduces a `tty_device` function, but we think its use in `open_getchr` is wrong. The previous use of `/dev/tty` looked for the controlling terminal, then if that did not work, used the standard error file descriptor. The new use of `ttyname(2)` always relies on the use of standard error. If standard error is redirected, less does not act as if it is connected to a terminal.

The example which we have identified is `man man 2>/dev/null`, which is obviously a few steps removed from less.

**Comment by gwsw** [comment] 2021-04-06 15:52
On systems I've tested, ttyname(2) returns NULL if stderr is redirected. In that case less uses /dev/tty. I don't see a case where redirecting stderr would behave as you describe. What system are you using where ```man man 2>/dev/null``` fails?

**Comment by gwsw** [comment] 2021-04-07 00:29
Never mind, I see the issue you're talking about when stderr is redirected. I will look into this.

**Comment by gwsw** [comment] 2021-04-07 00:55
This should be fixed in 6a1c6da22f117322c5338ecf6465a54cb4df7a51. I was a bit astray at first because it was actually caused by 2b224d352bc6231c2542e81b6a865d70f8c863f4 rather than 4d4e6f467663a60778be6fd22aa5273e73afebff

**Closed by gwsw** 2021-04-07 00:55 UTC

**Comment by zanchey** [comment] 2021-04-07 03:36
Indeed! Many thanks.
