### ISSUE TITLE
Garbled utf-8 strings

### ISSUE THREAD

**Issue by gAuk** [gwsw/less#519] opened 2024-05-26 11:43 UTC
Hello. 
I put a comment in the haskell code and it is garbled with utf-8 multibyte
The original text
--  ラマヌジャンのπ
Garbled text
-- 繝ｩ繝槭レ繧ｸ繝｣繝ｳ縺ｮﾏ

This is an example of a garbled code written in Japanese as "Ramanujan's pi". I don't know if multibyte is displayed on your PCs due to missing fonts here, but it is garbled anyway.

**Comment by avih** [comment] 2024-05-26 13:42
While I don't know the answer to this question, it would probably help to provide the following:
- Version of "less" (`less --version`).
- Which OS/distro.
- Which terminal.
- The output of the `locale` command (if not Windows).
- Is this a regression? I.e. do you have an earlier version of "less" where this worked correctly? If yes, in which version did it work correctly?

**Comment by gwsw** [comment] 2024-05-26 16:22
I copied the first text into a file and ran less on it and didn't see any problem. The fact that the "garbled" version has almost twice as many glyphs as the correct version indicates a misinterpretation of the encoding somewhere. Maybe the text is in UTF-8 but less and/or the terminal is using Shift-JIS or something like that?  Does it work better if you set ```LESSCHARSET=utf8``` in your environment?

**Comment by gAuk** [comment] 2024-05-28 07:18
This is my company's PC now, so the environment is a little different.
and the less command is another one.
but the phenomenon is the same:

> less --version
less 643 (Spencer V8 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

OS
Windows 10 Pro
Ver. 22H2
build  19045.4291

PowerShell7(x64)

locale
日本語（日本）
This locale means "ja_JP"

I have never used an older version than this.

> $LESSCHARSET="utf8"
> echo $LESSCHARSET
utf8

> echo "αβγ"  > test.txt
> less .\test.txt
ﾎｱﾎｲﾎｳ
.\test.txt (END)

> $LESSCHARSET="ja_JP.utf8"
> echo $LESSCHARSET
utf8
> less .\test.txt
ﾎｱﾎｲﾎｳ
.\test.txt (END)

> type .\test.txt
αβγ

> Get-Content .\test.txt | Format-Hex

   Label: String (System.String) <334A9921>

          Offset Bytes                                           Ascii
                 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
          ------ ----------------------------------------------- -----
0000000000000000 CE B1 CE B2 CE B3                               Î±Î²Î³

> less .\test.txt | Format-Hex

   Label: String (System.String) <7D36A2D5>

[32;1m          Offset[0m [32;1;3mBytes                                          [0m[32;1m Ascii[0m
[32;1m                [0m [32;1;3m00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F[0m[32;1m[0m
[32;1m          ------[0m [32;1m-----------------------------------------------[0m [32;1m-----[0m
0000000000000000 EF BE 8E EF BD B1 EF BE 8E EF BD B2 EF BE 8E EF ï¾�ï½±ï¾�ï½²ï¾�ï
0000000000000010 BD B3                                           ½³

> less .\test.txt | echo
ﾎｱﾎｲﾎｳ

By the way, "ﾎｱﾎｲﾎｳ" is pronounced "Hoah Hoy How" in Japanese. Pointless facts.

**Comment by avih** [comment] 2024-05-28 07:44
Can you please attach the file you're trying to view in "less" (zip it, and drag the zip into the comment).

Also, can you please post screenshots of how it looks bad in "less" for you, and how it looks correct elsewhere, e.g. maybe in "notepad"?

**Comment by gAuk** [comment] 2024-05-28 07:57
One thing became clear after that.
If you read the hexadecimal data "CE B1 CE B2 CE B3" of "αβγ" in utf-8, misunderstanding it as shif_jis, you will get "ﾎｱﾎｲﾎｳ".
NET runtime, is the old Japanese encoding "shift-jis" being interpreted and read?
See line 9 of the output below.
```shell
> python.exe .\encoding.py "CE B1 CE B2 CE B3"
Encoding: utf-8 -> Result: αβγ
Encoding: utf-8-sig -> Result: αβγ
Encoding: utf-16 -> Result: 뇎닎돎
Encoding: utf-16le -> Result: 뇎닎돎
Encoding: utf-16be -> Result: 캱캲캳
Encoding: utf-32 -> Result: Error: 'utf-32-le' codec can't decode bytes in position 0-3: code point not in range(0x110000)
Encoding: utf-32le -> Result: Error: 'utf-32-le' codec can't decode bytes in position 0-3: code point not in range(0x110000)
Encoding: utf-32be -> Result: Error: 'utf-32-be' codec can't decode bytes in position 0-3: code point not in range(0x110000)
Encoding: shift_jis -> Result: ﾎｱﾎｲﾎｳ
Encoding: euc-jp -> Result: 留硫粒
Encoding: iso-2022-jp -> Result: Error: 'iso2022_jp' codec can't decode byte 0xce in position 0: illegal multibyte sequence
```

The source of encoding.py is this
```python
import sys

def decode_hex_data(hex_data):
    byte_data = bytes.fromhex(hex_data)
    
    encodings = [
        "utf-8", "utf-8-sig",
        "utf-16", "utf-16le", "utf-16be",
        "utf-32", "utf-32le", "utf-32be",
        "shift_jis", "euc-jp", "iso-2022-jp"
    ]
    
    results = []
    
    for encoding in encodings:
        try:
            decoded_data = byte_data.decode(encoding)
            results.append((encoding, decoded_data))
        except Exception as e:
            results.append((encoding, f"Error: {e}"))
    
    return results

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python decode_hex.py <hex_data>")
        sys.exit(1)
    
    hex_data = sys.argv[1]
    results = decode_hex_data(hex_data)
    
    for encoding, result in results:
        print(f"Encoding: {encoding} -> Result: {result}")
```

**Comment by gAuk** [comment] 2024-05-28 08:07
Oh! less-v656 fixed it. Thank you!
```shell
> D:\less-v656\less-v656.exe .\test.txt
αβγ
.\test.txt (END)
```

**Comment by avih** [comment] 2024-05-28 08:12
For what it's worth, a file with the HEX content "CE B1 CE B2 CE B3" does show as "αβγ" for me in "less", which I think is correct:

![less-utf8](https://github.com/gwsw/less/assets/2164962/4f47cdfb-2e69-4788-acbd-a27cab5a63f4)

**Comment by gwsw** [comment] 2024-05-29 00:11
I don't fully understand why less-656 fixed the problem but I suspect it's because of the change avih mentioned that made the default charset be UTF-8. I don't think anything further needs to be done so I'm closing this.

**Closed by gwsw** 2024-05-29 00:11 UTC

**Comment by avih** [comment] 2024-05-29 00:28
For what it's worth, I also tested 643, and by default it indeed displays UTF-8 content incorrectly, but setting LESSCHARSET=utf8 does fix it for me with less-643.
