### ISSUE TITLE
alternative keyboard map characters not showing up in search

### ISSUE THREAD

**Issue by elig0n** [gwsw/less#277] opened 2022-09-05 06:30 UTC
I'm using Linux and less version 590. Xorg with Hebrew as an alternative keyboard map (setxkbmap).
I tried gnome-terminal, kitty and xfce4-terminal terminals and in none of them I could input Hebrew characters at the search field (after pressing `/`). 
Less would respond by 'blinking' the screen for each key press. 
There is no problem typing in the alternative layout elsewhere, i.e. in any of the terminals or other Xorg applications.
As far as I can remember it used to work previously.

**Comment by gwsw** [comment] 2022-09-05 18:11
I'm not very familiar with xorg or setxkbmap. In an xterm on Fedora 5.12.8, I ran less-590 and tried entering ctrl-shift-u followed by 05d1 and it correctly enters a bet character. Can you describe how I would set up your environment on a fedora system? You could also try the latest release (less-608), which has a couple of fixes in this area, although I'm doubtful as to whether it fixes this issue.

**Comment by elig0n** [comment] 2022-09-06 03:35
I did not succeed entering unicode char 05d1 in less in the form you showed in less' search 
while I did succeed doing it in the same terminal shell outside of less...

Using less-608 I could successfully enter Hebrew characters with no problem !

As for setting an environment, run from a terminal:

> setxkbmap -layout us,il -option grp:shifts_toggle

and then press both of your Shift keys together to toggle the keyboard input layout from US English to Hebrew and vice-versa.

**Comment by gwsw** [comment] 2022-09-06 15:01
I'm glad to hear the issue is fixed in less-608. In that case I don't think there's any point in investigating exactly why it doesn't work in less-590. Thanks for following up.

**Closed** 2022-09-07 09:49 UTC
