### ISSUE TITLE
Ctrl-C has no effect with + or -c (--clear-screen) option and process substitution

### ISSUE THREAD

**Issue by vinc17fr** [gwsw/less#12] opened 2019-06-29 01:54 UTC
An example with zsh (with process substitution instead of a pipe, the command producing data runs in background and is not interrupted by the Ctrl-C):

    less -fc <(echo foo; sleep 3; echo bar)

If I hit Ctrl-C during the `sleep 3`, it has no effect. This is due to the fact that to complete the screen display in the presence of a `+` or `-c` option, `less` still tries to take input into account.

I've reported the bug in the Debian BTS, with details on where the code yields the issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931216

This is an older `less` version (487), but the bug still occurs in version 551. I've attached [a patch there](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=931216;filename=less-eof-intr.patch;msg=19), which works for me, but I'm not sure that's the right way.

**Comment by gwsw** [comment] 2019-08-01 19:23
I wonder if the -c option should be removed. Originally it was intended to improve the visual appearance of the screen while repainting. But in almost all modern environments repainting is nearly instantaneous so there is no perceptible difference between using -c or not.

**Comment by vinc17fr** [comment] 2019-08-01 22:53
I use the -c option to get the contents at the top (when the number of lines is less than the one of the terminal). But perhaps there's another solution for that.

**Comment by gwsw** [comment] 2022-12-10 19:52
I believe this is fixed in less-617.

**Closed** 2022-12-29 20:09 UTC
Labels: awaiting close

**Comment by vinc17fr** [comment] 2022-12-30 00:13
I've just tested the current version from git on my example, and I confirm that this is fixed (both Ctrl-C and Ctrl-X now work). But since neither Debian nor Termux (Android) have upgraded yet, I couldn't test in my day-to-day work.
